# Site settings
title: Vlad Stirbu's blog
email: vstirbu@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.vladstirbu.com" # the base hostname & protocol for your site
twitter_username: VladStirbu
github_username:  vstirbu

# Build settings
markdown: kramdown

collections:
  - publications
  - projects
  - talks
